name: cloud_chat
description: Secure cloud chat.
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  get_it: ^7.2.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  onesignal_flutter: ^3.2.8
  flutter_secure_storage: ^5.0.2
  objectbox: ^1.3.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.4
  bubble: ^1.2.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/